/**
 * The service worker's two cache lists are hand-maintained, and nothing until
 * now checked them against the app. Three ways that goes wrong, all silent:
 *
 *   1. A file the app loads is in neither list. It is fetched from the network
 *      every time and the app breaks offline.
 *   2. A list names a file that no longer exists. `c.add` 404s during install,
 *      the app is half-cached, and offline mode fails on that one asset.
 *   3. A file is precached in HEAVY but `isHeavy()` does not recognise it, so
 *      it is *served* network-first while sitting in the cache untouched --
 *      with `cache: "reload"` refetching it in full on every load. This is the
 *      one that had 15 MB of meshes downloading on every avatar switch.
 *
 * All three are checked from the same source of truth: the module graph
 * reachable from index.html, plus the literal fetch() targets in it.
 *
 *   node test_sw_cache.mjs
 */
import { readFileSync, existsSync, readdirSync } from "node:fs";
import path from "node:path";

/* Assets the app fetches but deliberately treats as optional. Listing one here
 * is a decision, not a default: the app degrades quietly without it, so an
 * absent file is invisible in production and only this list records that we
 * meant it.
 *
 *   moment_arms.json -- generated by tools/moment_arms.py, not committed.
 *     loadMomentArms() swallows the 404, so the per-muscle moment-arm
 *     contributions in jointSubplot() simply never draw on the deployed site.
 *     Commit the file to turn that panel on, or leave it here to keep it off.
 */
const OPTIONAL = new Set([
  "moment_arms.json",
  // The README says this one may be deleted from a deployment to save 1.1 MB.
  // It is not cached, so ?demo=1 -- the step the README tells people to run
  // before granting camera access -- is the one thing that does not work
  // offline. Add it to SHELL if you want the demo to survive a flaky network.
  "reference.json",
]);

const norm = (p) => p.replace(/^\.\//, "").replace(/^\//, "");
const fail = [];
const check = (cond, msg) => { if (!cond) fail.push(msg); };

/* ---- 1. what sw.js declares ------------------------------------------- */

const sw = readFileSync("sw.js", "utf8");

const arrayNamed = (name) => {
  const m = sw.match(new RegExp(`const ${name}\\s*=\\s*\\[([\\s\\S]*?)\\];`));
  if (!m) throw new Error(`could not find ${name} in sw.js`);
  return [...m[1].matchAll(/"([^"]+)"/g)].map((x) => norm(x[1]));
};

const SHELL = arrayNamed("SHELL");
const HEAVY = arrayNamed("HEAVY");

const heavyBody = sw.match(/const isHeavy\s*=\s*\(url\)\s*=>([\s\S]*?);\n/);
if (!heavyBody) throw new Error("could not find isHeavy in sw.js");
const isHeavy = new Function("url", `return (${heavyBody[1]});`);
const heavyPath = (p) => isHeavy({ pathname: "/" + norm(p) });

/* ---- 2. what the app actually loads ------------------------------------ */

const local = (spec) => /^\.{0,2}\//.test(spec) && !spec.startsWith("//");
const IMPORT = /(?:^|\n)\s*import[\s\S]*?from\s*["']([^"']+)["']/g;
const FETCH = /fetch\(\s*["'`]([^"'`$]+)["'`]/g;

const seen = new Set();
const assets = new Set();
const queue = [];

// Specifiers are relative to the importing file: vendor/three.module.min.js
// pulls in "./three.core.min.js", which is vendor/three.core.min.js, not a
// file at the root.
const resolve = (spec, from) => norm(path.posix.join(path.posix.dirname(from), spec));

const scan = (src, from) => {
  for (const [, spec] of src.matchAll(IMPORT)) {
    if (!local(spec)) continue;
    const p = resolve(spec, from);
    if (!seen.has(p)) { seen.add(p); queue.push(p); }
  }
  for (const [, spec] of src.matchAll(FETCH)) {
    // Skip absolute URLs and unresolvable template interpolations.
    if (/^https?:/.test(spec)) continue;
    assets.add(resolve(spec, from));
  }
};

const html = readFileSync("index.html", "utf8");
for (const [, body] of html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)) scan(body, "index.html");

while (queue.length) {
  const p = queue.shift();
  assets.add(p);
  if (existsSync(p)) scan(readFileSync(p, "utf8"), p);
}

// meshes/${name}.{json,bin} is a template literal and cannot be resolved
// statically, so take every file that is actually there.
for (const f of readdirSync("meshes")) assets.add(`meshes/${f}`);

/* ---- 3. the three assertions ------------------------------------------ */

const cached = new Set([...SHELL, ...HEAVY]);

for (const a of assets) {
  if (OPTIONAL.has(a)) continue;
  check(cached.has(a), `loaded by the app but in neither SHELL nor HEAVY: ${a}`);
  check(existsSync(a), `loaded by the app but not present in the repo: ${a}`);
}

for (const p of cached) {
  check(existsSync(p) || p === "" || p.endsWith("/"),
        `listed in the service worker but missing from the repo: ${p}`);
}

for (const p of HEAVY) {
  check(heapCheck(p, true), `in HEAVY but isHeavy() says no, so it is precached and then served network-first anyway: ${p}`);
}
for (const p of SHELL) {
  if (p === "" || p.endsWith("/")) continue;
  check(heapCheck(p, false), `in SHELL but isHeavy() says yes, so it is served cache-first and a pushed fix cannot reach it: ${p}`);
}
function heapCheck(p, want) { return heavyPath(p) === want; }

/* ---- report ------------------------------------------------------------ */

if (fail.length) {
  console.error(`FAIL  ${fail.length} problem(s) in sw.js\n`);
  for (const f of fail) console.error("  - " + f);
  process.exit(1);
}
console.log(`ok    sw.js: ${assets.size} app assets, ${SHELL.length} shell + ${HEAVY.length} heavy, all consistent`);
